variables:
- group: my-custom-variables

pool:
  vmImage: 'ubuntu-16.04' # Hosted Ubuntu 1604
  demands: maven

trigger:
- master

steps:
- task: Maven@3
  displayName: 'Maven app/pom.xml'
  inputs:
    mavenPomFile: 'app/pom.xml'
    codeCoverageToolOption: Cobertura

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 
      echo $(Name)

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 
      echo '$(Tester)'